plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'uk.gov.moj'
version = '1.0.0'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-aspectj'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.5.RELEASE'
	implementation 'com.github.ben-manes.caffeine:caffeine:3.2.4'
	implementation 'com.opencsv:opencsv:5.10'

	compileOnly 'org.projectlombok:lombok:1.18.46'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	runtimeOnly 'io.micrometer:micrometer-registry-prometheus:1.17.0'
	runtimeOnly 'org.postgresql:postgresql:42.7.11'

	annotationProcessor 'org.projectlombok:lombok:1.18.46'

	testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-thymeleaf-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.springframework.security:spring-security-test:7.1.0'
	testImplementation 'org.testcontainers:junit-jupiter:1.21.3'
	testImplementation 'org.testcontainers:postgresql:1.21.3'
	testCompileOnly 'org.projectlombok:lombok:1.18.46'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.0.3'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

tasks.named('test') {
	useJUnitPlatform()
	exclude '**/*IT.class'
}

tasks.register('integrationTest', Test) {
	description = 'Runs integration tests - Requires Docker.'
	group = 'verification'
	useJUnitPlatform()
	testClassesDirs = sourceSets.test.output.classesDirs
	classpath = sourceSets.test.runtimeClasspath
	include '**/*IT.class'
	systemProperty 'cact.schema.sql', file('files/setup.sql').absolutePath
	shouldRunAfter tasks.named('test')
}

tasks.named('jar') {
	enabled = false
}

bootJar {
	archiveFileName = 'cact.jar'
	manifest {
		attributes 'Implementation-Title': project.name,
				'Implementation-Version': project.version
	}
}
