apiVersion: apps/v1
kind: Deployment
metadata:
  name: civil-appeal-case-tracker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: civil-appeal-case-tracker-app
  template:
    metadata:
      labels:
        app: civil-appeal-case-tracker-app
    spec:
      containers:
        - name: civil-appeal-case-tracker-app
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/dts-legacy/civil-appeal-case-tracker-preprod:civil-appeal-case-tracker-app-CIRCLE_SHA1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2000m"
              memory: "2048Mi"
            limits:
              cpu: "3000m"
              memory: "3072Mi"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_address
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_name
            - name: ENVIRONMENT
              value: preprod
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: case-tracker-csv-upload-login
                  key: admin_user
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: case-tracker-csv-upload-login
                  key: admin_pass
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 10
