package com.calander.util;

import com.calander.beans.Calander;
import org.hibernate.Session;
import au.com.bytecode.opencsv.CSVReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.text.MessageFormat;
import java.util.Arrays;

public class CsvProcessor {

    private static final Logger LOGGER = LoggerFactory.getLogger(CsvProcessor.class);

    /*
      The input data file contains 67 fields output by the source data system
      But only the first 25 fields are mapped to the database
      The id unique index field is generated by the insert statement

      We need to check that the csv processor doesn't extract data after column 25
     */
    public static int processCSV(CSVReader reader, Session session) throws IOException {
        String[] nextLine;
        Calander calander;
        int rowCount = 0;

        while ((nextLine = reader.readNext()) != null) {

            if (nextLine.length != 67) {
                LOGGER.error("Row " + rowCount + " has " + nextLine.length + " columns (expected 67)");
            } else {

                for (int i = 0; i < nextLine.length; i++) {

                    if (nextLine[i] != null && nextLine[i].contains("\uFEFF")) {
                        LOGGER.warn(MessageFormat.format(
                            "BOM detected and removed at row {0}, column {1}. Original value=[{2}]",
                            rowCount, i, nextLine[i]));

                        nextLine[i] = nextLine[i].replace("\uFEFF", "");
                    }
                }

            }
            calander = new Calander();
            calander.setProperties(nextLine);
            session.save(calander);
            session.flush();
            session.clear();
            rowCount++;
        }

        return rowCount;
    }
}