CREATE DATABASE CACT;

-- BEGIN: THIS IS A DEV PASSOWRD ONLY DO NOT USE IN ANYTHING PUBLICALLY ACCESSABLE OR FOR PRODUCTION SYSTEMS!
CREATE LOGIN cact_user WITH PASSWORD = 'cact_user';
-- END

use CACT;
CREATE USER cact_user FOR LOGIN cact_user WITH DEFAULT_SCHEMA=dbo;
GRANT SELECT, UPDATE, DELETE, INSERT TO cact_user;

EXEC sp_addrolemember N'db_owner', N'cact_user';

CREATE TABLE CACT.dbo.db_calander
(
  case_id INT PRIMARY KEY NOT NULL IDENTITY,
  search_date NVARCHAR(50) NULL,
  case_no NVARCHAR(50) NULL,
  heading_status NVARCHAR(255) NULL,
  judge1 NVARCHAR(255) NULL,
  judge2 NVARCHAR(255) NULL,
  judge3 NVARCHAR(255) NULL,
  lcourt NVARCHAR(255) NULL,
  venue NVARCHAR(255) NULL,
  case_ref NVARCHAR(50) NULL,
  title1 NVARCHAR(255) NULL,
  title2 NVARCHAR(255) NULL,
  type NVARCHAR(255) NULL,
  lc_judge NVARCHAR(255) NULL,
  nature NVARCHAR(255) NULL,
  last_updated NVARCHAR(50) NULL,
  result NVARCHAR(255) NULL,
  status NVARCHAR(255) NULL,
  track_line1 NVARCHAR(255) NULL,
  track_line2 NVARCHAR(255) NULL,
  track_line3 NVARCHAR(255) NULL,
  track_line4 NVARCHAR(255) NULL,
  track_line5 NVARCHAR(255) NULL,
  track_line6 NVARCHAR(255) NULL,
  track_line7 NVARCHAR(255) NULL,
  track_line8 NVARCHAR(255) NULL,
)
