apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: civil-appeal-case-tracker
  namespace: civil-appeal-case-tracker-prod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: civil-appeal-case-tracker-civil-appeal-case-tracker-prod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=dts-legacy"
    nginx.ingress.kubernetes.io/server-snippet: |
      location @custom_403 {
        return 403 "<h1>There is a problem:</h1><br><h3>Go back to the previous page using the back arrow and enter valid content</h3>";
      }
      error_page 403 @custom_403;
spec:
  ingressClassName: modsec
  tls:
    - hosts:
        - casetracker.justice.gov.uk
      secretName: casetracker-justice-app-secret
  rules:
    - host: casetracker.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: civil-appeal-case-tracker-app-service
                port:
                  number: 80
